stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn package
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test

deploy-github-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - git push github
    - echo "Application successfully deployed."
