stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  tags:
    - "kommod"
  script:
    - echo "Compiling the code..."
    - mvn package
    - echo "Compile complete."

unit-test-job:
  stage: test
  tags:
    - "kommod"
  script:
    - echo "Running unit tests..."
    - mvn test