name: kommod
title: kommod-cli
version: '0.0.2'
summary: The all in one tool for testing systems and containers
description: |
  This tool can be used to develop container applications and test them for 
  production use. Please note that at this time this tool is still under development...
grade: stable
confinement: strict
base: core18

website: https://kommod.app
issues: https://gitlab.com/kommod/kommod-cli/-/issues
license: MIT

architectures:
  - build-on: amd64

apps:
  kommod:
    command:
      java -jar -Duser.home=$SNAP_USER_DATA $SNAP/jar/kommod-cli-1.0-SNAPSHOT.jar
    plugs: [ home, network]

parts:
  kommod:
    source: https://github.com/Ben-Coepp-Publishing/kommod-cli.git
    source-tag: main
    source-type: git
    plugin: maven
    stage:
      - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
      - -etc/java-11-openjdk/security/blacklisted.certs lint-snap-v2_external_symlinks
    after:
      - kommod-commons

  kommod-commons:
    source: https://github.com/Ben-Coepp-Publishing/kommod-commons.git
    source-tag: main
    source-type: git
    plugin: maven
    maven-options: [install]
    stage:
      - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
      - -etc/java-11-openjdk/security/blacklisted.certs lint-snap-v2_external_symlinks